spring:
  spring:
    datasource:
      initialization-mode: always
      initialize: true
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password: password
      platform: h2
    h2:
      console:
        enabled: true # accessible via http://localhost:8080/h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update  # Automatically update the schema, set to 'create' for development, 'validate' for production
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  logging:
    level:
      org.h2: DEBUG
      org.springframework: INFO
      org.springframework.jdbc.core: DEBUG  # Shows DataSource initialization and script execution
      org.springframework.transaction: DEBUG  # Shows details about transaction management and script execution
      org.springframework.security: DEBUG
      org.springframework.aop: DEBUG
      org.springframework.security.oauth2: DEBUG
      org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
      org.springframework.boot.autoconfigure.jdbc: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.tool.schema: DEBUG
